### ISSUE TITLE
Replace Thread.sleep() implementation

### ISSUE THREAD

**Issue by chrisvasqm** [Alexis-LG/TestingJavaExercises#1]
It is recommended to avoid the use of the `Thread.sleep()`, and use Selenium's WebDriverWait `class` instead.

## Before
> https://github.com/Alexis-LG/TestingJavaExercises/blob/da7422ba6c81a80e871855e50474745b35008152/seleniumjava/src/test/java/DevToTests.java#L27

## After

```java
final WebDriverWait wait = new WebDriverWait(driver, 5);
wait.until(ExpectedConditions.urlContains("PLACEHOLDER"));
```

This implementation requires two new imports: `WebDriverWait` and `ExpectedConditions`, make use of any of `ExpectedConditions` methods in order to fit your needs.

**Comment by Alexis-LG** [comment]
Done. Thanks for the tip.
